kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
  labels:
    {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Release.Name }}