---
apiVersion: apps/v1              #当前格式的版本
kind: Deployment                 #当前创建资源的类型， 当前类型是Deployment
metadata:                        #当前资源的元数据
  name: nugetserver              #当前资源的名字 是元数据必须的项
spec:                            #是当前Deployment的规格说明
  replicas: 2                    #指当前创建的副本数量 默认不填 默认值就为‘1’
  selector:
    matchLabels:
      app: nugetserver
  template:                      #定义pod的模板
    metadata:                    #当前pod的元数据
      labels:                    #至少顶一个labels标签，可任意创建一个 key:value
        app: nugetserver
    spec:                        #当前pod的规格说明
      containers:                #容器
      - name: nugetserver              #是容器的名字容器名字是必须填写的
        image: micacr.azurecr.cn/images/nugetserver:v1.1      #镜像 镜像的名字和版本
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
          - name: azure-nuget-packages
            mountPath: /home/nugets
      volumes:
      - name: azure-nuget-packages
        persistentVolumeClaim:
          claimName: nuget-packages