---
apiVersion: v1
kind: Secret
data:
  azurestorageaccountname: bWljYWtzc3RvcmFnZQ==
  azurestorageaccountkey: dlNsQnhxUFRFNlU2L1ZYOVBlMHY3aUpYYlRUa09UVFNGOWQyRVpVaGxtV1ZFa2FEdHo5cWJrbDgzdjJ3U3E2WTJpVmNsS2szdk5iTjVFSFBSRWVIWVE9PQ==
metadata:
  creationTimestamp: null
  name: azure-nuget-secret